targets:
  $default:
    builders:
      freezed:
        options:
          # Customization options for freezed
          union_key: "type"
          union_value_case: "pascal"
      json_serializable:
        options:
          explicit_to_json: true
