// File generated by FlutterFire CLI for DEVELOPMENT environment.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Development [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevelopmentFirebaseOptions.currentPlatform,
/// );
/// ```
class DevelopmentFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlN3avZ-T2OnFFU7A7b6jshV3FPOc5pE',
    appId: '1:487033381743:web:715a4f67cc76c77f56fe9a',
    messagingSenderId: '487033381743',
    projectId: 'budgetpillarsdev',
    authDomain: 'budgetpillarsdev.firebaseapp.com',
    storageBucket: 'budgetpillarsdev.firebasestorage.app',
    measurementId: 'G-HZ79MLQCE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSSx80_KO-BBxzT7PsFnIY2tJA2Ru6g8I',
    appId: '1:487033381743:android:084b0794211a73c456fe9a',
    messagingSenderId: '487033381743',
    projectId: 'budgetpillarsdev',
    storageBucket: 'budgetpillarsdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8JlM87Rvb7jo710MPJbuDbhjoq_eM3VU',
    appId: '1:487033381743:ios:3ee7f4e77d252de756fe9a',
    messagingSenderId: '487033381743',
    projectId: 'budgetpillarsdev',
    storageBucket: 'budgetpillarsdev.firebasestorage.app',
    iosClientId:
        '487033381743-n2v8fqp46i4qa7vtq8cocnlu0r9a982k.apps.googleusercontent.com',
    iosBundleId: 'budgetpillars.lojinnovation.com.easyBudgetPillars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8JlM87Rvb7jo710MPJbuDbhjoq_eM3VU',
    appId: '1:487033381743:ios:3ee7f4e77d252de756fe9a',
    messagingSenderId: '487033381743',
    projectId: 'budgetpillarsdev',
    storageBucket: 'budgetpillarsdev.firebasestorage.app',
    iosClientId:
        '487033381743-n2v8fqp46i4qa7vtq8cocnlu0r9a982k.apps.googleusercontent.com',
    iosBundleId: 'budgetpillars.lojinnovation.com.easyBudgetPillars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqlN3avZ-T2OnFFU7A7b6jshV3FPOc5pE',
    appId: '1:487033381743:web:94227b0359ae47fc56fe9a',
    messagingSenderId: '487033381743',
    projectId: 'budgetpillarsdev',
    authDomain: 'budgetpillarsdev.firebaseapp.com',
    storageBucket: 'budgetpillarsdev.firebasestorage.app',
    measurementId: 'G-N8F9ZBPWVS',
  );
}
